### ISSUE TITLE
Tracking ticket: Version 1.0

### ISSUE THREAD

**Issue by guidobouman** [guidobouman/panelsnap#116]
For version 1.0 I'm shaking up things a bit for jQuery-panelSnap:

jQuery-panelSnap will:
- [x] get renamed to PanelSnap.
- [x] become framework agnostic so that it can be used with jQuery, Angular, React and Vue.
- [x] drop support for IE8 and below to save on development time.
- [x] add support for horizontal snapping.
- [ ] ~get documentation on using PanelSnap with jQuery, Vue & React.~

Please nominate other requests for PanelSnap in the discussion below.

**Comment by guidobouman** [comment]
Moving documentation updates out of the release. We can finally publish v1.0!
